import './globals.css';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

export const metadata = {
  title: 'Rural Web Factory',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body
        id="top"
        className="changeMode font-textFont text-textColor bg-primary"
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
